Notes

24 Feb

Curve does not work properly
there is a problem with interpolating between the general curves
they are to sharp and the interpolation does not work nicely even with bernstein interpolation
have a look at this interpolation again

interpolation for the individual curves
might not work either it is not going to the right end point



25 Feb guide Curve works
maybe change height to a vector
